### ISSUE TITLE
RateLimiter class missing in vendor/autoload.php

### ISSUE THREAD

**Issue by martin-tomasek** [jaggedsoft/php-binance-api#242]
**RateLimiter class missing in vendor/autoload.php**
- bug: autoload.php contains only class Binance\API, but does not contain a class Binance\RateLimiter.
  
**Platform:**
- Docker unix cointainer on Windows host, Zend Framework 2

**php version:**
- 7.0.0

**Long descrption**
- I installed php-binance-api via composer (composer require jaggedsoft/php-binance-api). My autoloader does not contain a class Binance\RateLimiter. Just class Binance\API. I tried to regenerate autoloader class several times (composer dumpautoload) but class  Binance\RateLimiter still missing. I had to include it manually, it doesn't look good in Zend-Framework..

**code**
```php
require 'vendor/autoload.php';
$api = new Binance\API( "<api key>","<secret>" );
$api = new Binance\RateLimiter($api);
while(true) {
   $api->openOrders("BNBBTC"); // rate limited
}
```

**result**
```
Fatal error: Uncaught Error: Class 'Binance\RateLimiter' not found in /var/www/module/Application/src/Application/Controller/ConsoleController.php:32
Stack trace:
#0 /var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Application\Controller\ConsoleController->checkLoansAction()
#1 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#2 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#3 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#4 /var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /var/www/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(O in /var/www/module/Application/src/Application/Controller/ConsoleController.php on line 32
```

thank you

**Comment by martin-tomasek** [comment]
![image](https://user-images.githubusercontent.com/16007358/61760141-d892a900-adca-11e9-9306-a7dc028df7d0.png)
