### ISSUE TITLE
websockets are not working

### ISSUE THREAD

**Issue by sgk54** [jaggedsoft/php-binance-api#497]
websocket not working

error message as below

Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\uri_for() in C:\xampp\htdocs\p1\vendor\ratchet\pawl\src\Connector.php:126 Stack trace: #0 C:\xampp\htdocs\p1\vendor\ratchet\pawl\src\Connector.php(38): Ratchet\Client\Connector->generateRequest('wss://stream.bi...', Array, Array) #1 C:\xampp\htdocs\p1\vendor\jaggedsoft\php-binance-api\php-binance-api.php(2361): Ratchet\Client\Connector->__invoke('wss://stream.bi...') #2 C:\xampp\htdocs\p1\ws1.php(5): Binance\API->chart(Array, '1m', Object(Closure)) #3 {main} thrown in C:\xampp\htdocs\p1\vendor\ratchet\pawl\src\Connector.php on line 126

  using XAMPP for Windows 8.2.4

**Comment by sgk54** [comment]
No reply is observed from developer of the code. Better to delete the thread and remove the library. Use other programming language.
